/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autovaluetest;

public class LibraryTest {
	// @Test public void testSomeLibraryMethod() {
	// Library classUnderTest = new Library();
	// assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	// }
}
